export const ScreenList = {
  SPLASHSCREEN: "SplashScreen",
  DASHBOARD: "DashBoard",
  ContactUs: "Contact Us",
  LANGUAGES: "Languages",
  PRIVACY_POLICY: "Privacy Policy",
  TERMS_CONDITIONS: "Terms & Conditions",
  ABOUS_US: "About App",
  SHLOCK_INTRO: "ShlockIntro",
  ABOUT_SWAMI: "SwamiDetails",
  SHLOCKS: "ShlockList",
  PLAYERSCREEN: "PlayerScreen",
};

export const Fonts = {
  Poppins_100Thin: "Poppins_100Thin",
  Poppins_100Thin_Italic: "Poppins_100Thin_Italic",
  Poppins_200ExtraLight: "Poppins_200ExtraLight",
  Poppins_200ExtraLight_Italic: "Poppins_200ExtraLight_Italic",
  Poppins_300Light: "Poppins_300Light",
  Poppins_300Light_Italic: "Poppins_300Light_Italic",
  Poppins_400Regular: "Poppins_400Regular",
  Poppins_400Regular_Italic: "Poppins_400Regular_Italic",
  Poppins_500Medium: "Poppins_500Medium",
  Poppins_500Medium_Italic: "Poppins_500Medium_Italic",
  Poppins_600SemiBold: "Poppins_600SemiBold",
  Poppins_600SemiBold_Italic: "Poppins_600SemiBold_Italic",
  Poppins_700Bold: "Poppins_700Bold",
  Poppins_700Bold_Italic: "Poppins_700Bold_Italic",
  Poppins_800ExtraBold: "Poppins_800ExtraBold",
  Poppins_800ExtraBold_Italic: "Poppins_800ExtraBold_Italic",
  Poppins_900Black: "Poppins_900Black",
  Poppins_900Black_Italic: "Poppins_900Black_Italic",
};
